### ISSUE TITLE
About SFD_loss

### ISSUE THREAD

**Issue by yihui1230** [Mryao-yuan/SFBI-Net#1]
Thank you for your open source work. However, i believe that  lines 202 to 204 of the SFBI-Net.py is  inconsistent with the content about SFD_loss in paper, because the maxpool_2d is  imposed on the spatial dimension rather than the channel dimension described in the paper.

**Comment by Mryao-yuan** [comment]
Thank you for your attention and feedback on my open source! 
Regarding the inconsistency you mentioned between lines 202 to 204 of the SFBI-NEt.py file and the description of the SFD_loss in the paper, I have thoroughly reviewed the relevant code. I can confirm that the maxpool_2d operation is indeed conducted along the spatial dimension. The discrepancy arose due to inconsistencies between the server code and the version uploaded, which led to this oversight. Before pooling, the input feature dimensions are (b, h, w, c), ensuring that pooling is performed along the channel dimension. This approach aligns with the method described in the paper. Thank you for your correction; we will address this issue and provide the necessary updates.
